// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/index.tsx";
import * as $1 from "./routes/posts/[slug].tsx";
import * as $$0 from "./islands/About.tsx";

const manifest = {
  routes: {
    "./routes/index.tsx": $0,
    "./routes/posts/[slug].tsx": $1,
  },
  islands: {
    "./islands/About.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
